spring.application.name=ChildVaccinationDiary
###CONFIG###
spring.config.import=optional:file:_env[.properties]
#------- connection --------------------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
#-------- DB ----------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRESDB_USERNAME}
spring.datasource.password=${POSTGRESDB_PASSWORD}
#-------- liquibase --------------------
spring.liquibase.enabled=true
spring.liquibase.changeLog=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=${DB_URL}
spring.liquibase.user=${POSTGRESDB_USERNAME}
spring.liquibase.password=${POSTGRESDB_PASSWORD}
#------- settings ----------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.servlet.context-path=/api
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#------- security ----------------------
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}
#------- mail --------------------------
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

