spring.datasource.url= jdbc:postgresql://teamproject:mwPYph4dT4C99Db8HFND7hcRTNebkaSx@dpg-cuguq2ggph6c73d6b5gg-a.frankfurt-postgres.render.com/kidty_db
spring.datasource.username=teamproject
spring.datasource.password=mwPYph4dT4C99Db8HFND7hcRTNebkaSx

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
