spring.config.import=optional:file:_env[.properties]
spring.datasource.url= ${DB_URL}
spring.datasource.username=${POSTGRESDB_USERNAME}
spring.datasource.password=${POSTGRESDB_PASSWORD}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
